
on: push
jobs:
  insiders-build:
    strategy:
      matrix:
        os: [windows, ubuntu]
        include:
          - os: windows
            build: npx caxa --input . --output "ayanbot.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/index.js" "CAXA"
            artifact: ayanbot.exe
          - os: ubuntu
             build: |
               npx caxa --input . --output "ayanbot" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/index.js" "CAXA"
               tar -czf "ayanbot-linux.tgz" "ayanbot"
             artifact: ayanbot-linux.tgz
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: |
          npm ci
          ${{ matrix.build }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ insiders-build ]
    runs-on: ubuntu-latest
    steps:
      - run: zip -czf "ayanbot-windows.zip" "ayanbot.exe"
      - uses: actions/download-artifact@v2
        with:
          name: ayanbot-windows.zip
      - uses: actions/download-artifact@v2
        with:
          name: ayanbot-macos.tgz
      - uses: actions/download-artifact@v2
        with:
          name: ayanbot-linux.tgz
      - run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        id: tag
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ayanbot-windows.zip
          asset_name: ayanbot-windows-${{ steps.tag.outputs.tag }}.zip
          asset_content_type: application/vnd.microsoft.portable-executable
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ayanbot-linux.tgz
          asset_name: ayanbot-linux-${{ steps.tag.outputs.tag }}.tgz
          asset_content_type: application/gzip